import DQN

FIELD_SIZE = 40
STACKED_OBSERVATION = 5
GAMMA = 0.9

ITERATION = 1000
epsilon = 0.01

env = DQN.environment(FIELD_SIZE)
agent = DQN.DQNAgent(env, FIELD_SIZE, STACKED_OBSERVATION, GAMMA)
DQN.train(agent, ITERATION, epsilon)
